#pragma once
// Declares the Badge Pirates skull mark image asset (Nexus 176cc276 splash
// screen). See src/UI/img_bp_skull.c - generated by
// scripts/gen_splash_skull.py, do not hand-edit.
#include <lvgl.h>

LV_IMAGE_DECLARE(img_bp_skull);
